// List of country codes with flags for the phone dropdown
export const countryCodes = [
  { code: "AF", dialCode: "+93", flag: "🇦🇫", country: "Afghanistan" },
  { code: "AL", dialCode: "+355", flag: "🇦🇱", country: "Albania" },
  { code: "DZ", dialCode: "+213", flag: "🇩🇿", country: "Algeria" },
  { code: "AS", dialCode: "+1-684", flag: "🇦🇸", country: "American Samoa" },
  { code: "AD", dialCode: "+376", flag: "🇦🇩", country: "Andorra" },
  { code: "AO", dialCode: "+244", flag: "🇦🇴", country: "Angola" },
  { code: "AI", dialCode: "+1-264", flag: "🇦🇮", country: "Anguilla" },
  { code: "AG", dialCode: "+1-268", flag: "🇦🇬", country: "Antigua and Barbuda" },
  { code: "AR", dialCode: "+54", flag: "🇦🇷", country: "Argentina" },
  { code: "AM", dialCode: "+374", flag: "🇦🇲", country: "Armenia" },
  { code: "AW", dialCode: "+297", flag: "🇦🇼", country: "Aruba" },
  { code: "AU", dialCode: "+61", flag: "🇦🇺", country: "Australia" },
  { code: "AT", dialCode: "+43", flag: "🇦🇹", country: "Austria" },
  { code: "AZ", dialCode: "+994", flag: "🇦🇿", country: "Azerbaijan" },
  { code: "BS", dialCode: "+1-242", flag: "🇧🇸", country: "Bahamas" },
  { code: "BH", dialCode: "+973", flag: "🇧🇭", country: "Bahrain" },
  { code: "BD", dialCode: "+880", flag: "🇧🇩", country: "Bangladesh" },
  { code: "BB", dialCode: "+1-246", flag: "🇧🇧", country: "Barbados" },
  { code: "BY", dialCode: "+375", flag: "🇧🇾", country: "Belarus" },
  { code: "BE", dialCode: "+32", flag: "🇧🇪", country: "Belgium" },
  { code: "BZ", dialCode: "+501", flag: "🇧🇿", country: "Belize" },
  { code: "BJ", dialCode: "+229", flag: "🇧🇯", country: "Benin" },
  { code: "BM", dialCode: "+1-441", flag: "🇧🇲", country: "Bermuda" },
  { code: "BT", dialCode: "+975", flag: "🇧🇹", country: "Bhutan" },
  { code: "BO", dialCode: "+591", flag: "🇧🇴", country: "Bolivia" },
  { code: "BA", dialCode: "+387", flag: "🇧🇦", country: "Bosnia and Herzegovina" },
  { code: "BW", dialCode: "+267", flag: "🇧🇼", country: "Botswana" },
  { code: "BR", dialCode: "+55", flag: "🇧🇷", country: "Brazil" },
  { code: "BN", dialCode: "+673", flag: "🇧🇳", country: "Brunei" },
  { code: "BG", dialCode: "+359", flag: "🇧🇬", country: "Bulgaria" },
  { code: "BF", dialCode: "+226", flag: "🇧🇫", country: "Burkina Faso" },
  { code: "BI", dialCode: "+257", flag: "🇧🇮", country: "Burundi" },
  { code: "KH", dialCode: "+855", flag: "🇰🇭", country: "Cambodia" },
  { code: "CM", dialCode: "+237", flag: "🇨🇲", country: "Cameroon" },
  { code: "CA", dialCode: "+1", flag: "🇨🇦", country: "Canada" },
  { code: "CV", dialCode: "+238", flag: "🇨🇻", country: "Cape Verde" },
  { code: "KY", dialCode: "+1-345", flag: "🇰🇾", country: "Cayman Islands" },
  { code: "CF", dialCode: "+236", flag: "🇨🇫", country: "Central African Republic" },
  { code: "TD", dialCode: "+235", flag: "🇹🇩", country: "Chad" },
  { code: "CL", dialCode: "+56", flag: "🇨🇱", country: "Chile" },
  { code: "CN", dialCode: "+86", flag: "🇨🇳", country: "China" },
  { code: "CO", dialCode: "+57", flag: "🇨🇴", country: "Colombia" },
  { code: "KM", dialCode: "+269", flag: "🇰🇲", country: "Comoros" },
  { code: "CG", dialCode: "+242", flag: "🇨🇬", country: "Congo" },
  { code: "CR", dialCode: "+506", flag: "🇨🇷", country: "Costa Rica" },
  { code: "HR", dialCode: "+385", flag: "🇭🇷", country: "Croatia" },
  { code: "CU", dialCode: "+53", flag: "🇨🇺", country: "Cuba" },
  { code: "CY", dialCode: "+357", flag: "🇨🇾", country: "Cyprus" },
  { code: "CZ", dialCode: "+420", flag: "🇨🇿", country: "Czech Republic" },
  { code: "DK", dialCode: "+45", flag: "🇩🇰", country: "Denmark" },
  { code: "DJ", dialCode: "+253", flag: "🇩🇯", country: "Djibouti" },
  { code: "DM", dialCode: "+1-767", flag: "🇩🇲", country: "Dominica" },
  { code: "DO", dialCode: "+1-809", flag: "🇩🇴", country: "Dominican Republic" },
  { code: "EC", dialCode: "+593", flag: "🇪🇨", country: "Ecuador" },
  { code: "EG", dialCode: "+20", flag: "🇪🇬", country: "Egypt" },
  { code: "SV", dialCode: "+503", flag: "🇸🇻", country: "El Salvador" },
  { code: "GQ", dialCode: "+240", flag: "🇬🇶", country: "Equatorial Guinea" },
  { code: "ER", dialCode: "+291", flag: "🇪🇷", country: "Eritrea" },
  { code: "EE", dialCode: "+372", flag: "🇪🇪", country: "Estonia" },
  { code: "ET", dialCode: "+251", flag: "🇪🇹", country: "Ethiopia" },
  { code: "FJ", dialCode: "+679", flag: "🇫🇯", country: "Fiji" },
  { code: "FI", dialCode: "+358", flag: "🇫🇮", country: "Finland" },
  { code: "FR", dialCode: "+33", flag: "🇫🇷", country: "France" },
  { code: "GA", dialCode: "+241", flag: "🇬🇦", country: "Gabon" },
  { code: "GM", dialCode: "+220", flag: "🇬🇲", country: "Gambia" },
  { code: "GE", dialCode: "+995", flag: "🇬🇪", country: "Georgia" },
  { code: "DE", dialCode: "+49", flag: "🇩🇪", country: "Germany" },
  { code: "GH", dialCode: "+233", flag: "🇬🇭", country: "Ghana" },
  { code: "GR", dialCode: "+30", flag: "🇬🇷", country: "Greece" },
  { code: "GL", dialCode: "+299", flag: "🇬🇱", country: "Greenland" },
  { code: "GD", dialCode: "+1-473", flag: "🇬🇩", country: "Grenada" },
  { code: "GU", dialCode: "+1-671", flag: "🇬🇺", country: "Guam" },
  { code: "GT", dialCode: "+502", flag: "🇬🇹", country: "Guatemala" },
  { code: "GN", dialCode: "+224", flag: "🇬🇳", country: "Guinea" },
  { code: "GW", dialCode: "+245", flag: "🇬🇼", country: "Guinea-Bissau" },
  { code: "GY", dialCode: "+592", flag: "🇬🇾", country: "Guyana" },
  { code: "HT", dialCode: "+509", flag: "🇭🇹", country: "Haiti" },
  { code: "HN", dialCode: "+504", flag: "🇭🇳", country: "Honduras" },
  { code: "HK", dialCode: "+852", flag: "🇭🇰", country: "Hong Kong" },
  { code: "HU", dialCode: "+36", flag: "🇭🇺", country: "Hungary" },
  { code: "IS", dialCode: "+354", flag: "🇮🇸", country: "Iceland" },
  { code: "IN", dialCode: "+91", flag: "🇮🇳", country: "India" },
  { code: "ID", dialCode: "+62", flag: "🇮🇩", country: "Indonesia" },
  { code: "IR", dialCode: "+98", flag: "🇮🇷", country: "Iran" },
  { code: "IQ", dialCode: "+964", flag: "🇮🇶", country: "Iraq" },
  { code: "IE", dialCode: "+353", flag: "🇮🇪", country: "Ireland" },
  { code: "IL", dialCode: "+972", flag: "🇮🇱", country: "Israel" },
  { code: "IT", dialCode: "+39", flag: "🇮🇹", country: "Italy" },
  { code: "JM", dialCode: "+1-876", flag: "🇯🇲", country: "Jamaica" },
  { code: "JP", dialCode: "+81", flag: "🇯🇵", country: "Japan" },
  { code: "JO", dialCode: "+962", flag: "🇯🇴", country: "Jordan" },
  { code: "KZ", dialCode: "+7", flag: "🇰🇿", country: "Kazakhstan" },
  { code: "KE", dialCode: "+254", flag: "🇰🇪", country: "Kenya" },
  { code: "KI", dialCode: "+686", flag: "🇰🇮", country: "Kiribati" },
  { code: "KP", dialCode: "+850", flag: "🇰🇵", country: "North Korea" },
  { code: "KR", dialCode: "+82", flag: "🇰🇷", country: "South Korea" },
  { code: "KW", dialCode: "+965", flag: "🇰🇼", country: "Kuwait" },
  { code: "KG", dialCode: "+996", flag: "🇰🇬", country: "Kyrgyzstan" },
  { code: "LA", dialCode: "+856", flag: "🇱🇦", country: "Laos" },
  { code: "LV", dialCode: "+371", flag: "🇱🇻", country: "Latvia" },
  { code: "LB", dialCode: "+961", flag: "🇱🇧", country: "Lebanon" },
  { code: "LS", dialCode: "+266", flag: "🇱🇸", country: "Lesotho" },
  { code: "LR", dialCode: "+231", flag: "🇱🇷", country: "Liberia" },
  { code: "LY", dialCode: "+218", flag: "🇱🇾", country: "Libya" },
  { code: "LI", dialCode: "+423", flag: "🇱🇮", country: "Liechtenstein" },
  { code: "LT", dialCode: "+370", flag: "🇱🇹", country: "Lithuania" },
  { code: "LU", dialCode: "+352", flag: "🇱🇺", country: "Luxembourg" },
  { code: "MO", dialCode: "+853", flag: "🇲🇴", country: "Macao" },
  { code: "MK", dialCode: "+389", flag: "🇲🇰", country: "Macedonia" },
  { code: "MG", dialCode: "+261", flag: "🇲🇬", country: "Madagascar" },
  { code: "MW", dialCode: "+265", flag: "🇲🇼", country: "Malawi" },
  { code: "MY", dialCode: "+60", flag: "🇲🇾", country: "Malaysia" },
  { code: "MV", dialCode: "+960", flag: "🇲🇻", country: "Maldives" },
  { code: "ML", dialCode: "+223", flag: "🇲🇱", country: "Mali" },
  { code: "MT", dialCode: "+356", flag: "🇲🇹", country: "Malta" },
  { code: "MH", dialCode: "+692", flag: "🇲🇭", country: "Marshall Islands" },
  { code: "MR", dialCode: "+222", flag: "🇲🇷", country: "Mauritania" },
  { code: "MU", dialCode: "+230", flag: "🇲🇺", country: "Mauritius" },
  { code: "MX", dialCode: "+52", flag: "🇲🇽", country: "Mexico" },
  { code: "FM", dialCode: "+691", flag: "🇫🇲", country: "Micronesia" },
  { code: "MD", dialCode: "+373", flag: "🇲🇩", country: "Moldova" },
  { code: "MC", dialCode: "+377", flag: "🇲🇨", country: "Monaco" },
  { code: "MN", dialCode: "+976", flag: "🇲🇳", country: "Mongolia" },
  { code: "ME", dialCode: "+382", flag: "🇲🇪", country: "Montenegro" },
  { code: "MS", dialCode: "+1-664", flag: "🇲🇸", country: "Montserrat" },
  { code: "MA", dialCode: "+212", flag: "🇲🇦", country: "Morocco" },
  { code: "MZ", dialCode: "+258", flag: "🇲🇿", country: "Mozambique" },
  { code: "MM", dialCode: "+95", flag: "🇲🇲", country: "Myanmar" },
  { code: "NA", dialCode: "+264", flag: "🇳🇦", country: "Namibia" },
  { code: "NR", dialCode: "+674", flag: "🇳🇷", country: "Nauru" },
  { code: "NP", dialCode: "+977", flag: "🇳🇵", country: "Nepal" },
  { code: "NL", dialCode: "+31", flag: "🇳🇱", country: "Netherlands" },
  { code: "NZ", dialCode: "+64", flag: "🇳🇿", country: "New Zealand" },
  { code: "NI", dialCode: "+505", flag: "🇳🇮", country: "Nicaragua" },
  { code: "NE", dialCode: "+227", flag: "🇳🇪", country: "Niger" },
  { code: "NG", dialCode: "+234", flag: "🇳🇬", country: "Nigeria" },
  { code: "NO", dialCode: "+47", flag: "🇳🇴", country: "Norway" },
  { code: "OM", dialCode: "+968", flag: "🇴🇲", country: "Oman" },
  { code: "PK", dialCode: "+92", flag: "🇵🇰", country: "Pakistan" },
  { code: "PW", dialCode: "+680", flag: "🇵🇼", country: "Palau" },
  { code: "PS", dialCode: "+970", flag: "🇵🇸", country: "Palestine" },
  { code: "PA", dialCode: "+507", flag: "🇵🇦", country: "Panama" },
  { code: "PG", dialCode: "+675", flag: "🇵🇬", country: "Papua New Guinea" },
  { code: "PY", dialCode: "+595", flag: "🇵🇾", country: "Paraguay" },
  { code: "PE", dialCode: "+51", flag: "🇵🇪", country: "Peru" },
  { code: "PH", dialCode: "+63", flag: "🇵🇭", country: "Philippines" },
  { code: "PL", dialCode: "+48", flag: "🇵🇱", country: "Poland" },
  { code: "PT", dialCode: "+351", flag: "🇵🇹", country: "Portugal" },
  { code: "PR", dialCode: "+1-787", flag: "🇵🇷", country: "Puerto Rico" },
  { code: "QA", dialCode: "+974", flag: "🇶🇦", country: "Qatar" },
  { code: "RO", dialCode: "+40", flag: "🇷🇴", country: "Romania" },
  { code: "RU", dialCode: "+7", flag: "🇷🇺", country: "Russia" },
  { code: "RW", dialCode: "+250", flag: "🇷🇼", country: "Rwanda" },
  { code: "KN", dialCode: "+1-869", flag: "🇰🇳", country: "Saint Kitts and Nevis" },
  { code: "LC", dialCode: "+1-758", flag: "🇱🇨", country: "Saint Lucia" },
  { code: "VC", dialCode: "+1-784", flag: "🇻🇨", country: "Saint Vincent and the Grenadines" },
  { code: "WS", dialCode: "+685", flag: "🇼🇸", country: "Samoa" },
  { code: "SM", dialCode: "+378", flag: "🇸🇲", country: "San Marino" },
  { code: "ST", dialCode: "+239", flag: "🇸🇹", country: "Sao Tome and Principe" },
  { code: "SA", dialCode: "+966", flag: "🇸🇦", country: "Saudi Arabia" },
  { code: "SN", dialCode: "+221", flag: "🇸🇳", country: "Senegal" },
  { code: "RS", dialCode: "+381", flag: "🇷🇸", country: "Serbia" },
  { code: "SC", dialCode: "+248", flag: "🇸🇨", country: "Seychelles" },
  { code: "SL", dialCode: "+232", flag: "🇸🇱", country: "Sierra Leone" },
  { code: "SG", dialCode: "+65", flag: "🇸🇬", country: "Singapore" },
  { code: "SK", dialCode: "+421", flag: "🇸🇰", country: "Slovakia" },
  { code: "SI", dialCode: "+386", flag: "🇸🇮", country: "Slovenia" },
  { code: "SB", dialCode: "+677", flag: "🇸🇧", country: "Solomon Islands" },
  { code: "SO", dialCode: "+252", flag: "🇸🇴", country: "Somalia" },
  { code: "ZA", dialCode: "+27", flag: "🇿🇦", country: "South Africa" },
  { code: "SS", dialCode: "+211", flag: "🇸🇸", country: "South Sudan" },
  { code: "ES", dialCode: "+34", flag: "🇪🇸", country: "Spain" },
  { code: "LK", dialCode: "+94", flag: "🇱🇰", country: "Sri Lanka" },
  { code: "SD", dialCode: "+249", flag: "🇸🇩", country: "Sudan" },
  { code: "SR", dialCode: "+597", flag: "🇸🇷", country: "Suriname" },
  { code: "SZ", dialCode: "+268", flag: "🇸🇿", country: "Swaziland" },
  { code: "SE", dialCode: "+46", flag: "🇸🇪", country: "Sweden" },
  { code: "CH", dialCode: "+41", flag: "🇨🇭", country: "Switzerland" },
  { code: "SY", dialCode: "+963", flag: "🇸🇾", country: "Syria" },
  { code: "TW", dialCode: "+886", flag: "🇹🇼", country: "Taiwan" },
  { code: "TJ", dialCode: "+992", flag: "🇹🇯", country: "Tajikistan" },
  { code: "TZ", dialCode: "+255", flag: "🇹🇿", country: "Tanzania" },
  { code: "TH", dialCode: "+66", flag: "🇹🇭", country: "Thailand" },
  { code: "TL", dialCode: "+670", flag: "🇹🇱", country: "Timor-Leste" },
  { code: "TG", dialCode: "+228", flag: "🇹🇬", country: "Togo" },
  { code: "TO", dialCode: "+676", flag: "🇹🇴", country: "Tonga" },
  { code: "TT", dialCode: "+1-868", flag: "🇹🇹", country: "Trinidad and Tobago" },
  { code: "TN", dialCode: "+216", flag: "🇹🇳", country: "Tunisia" },
  { code: "TR", dialCode: "+90", flag: "🇹🇷", country: "Turkey" },
  { code: "TM", dialCode: "+993", flag: "🇹🇲", country: "Turkmenistan" },
  { code: "TC", dialCode: "+1-649", flag: "🇹🇨", country: "Turks and Caicos Islands" },
  { code: "TV", dialCode: "+688", flag: "🇹🇻", country: "Tuvalu" },
  { code: "UG", dialCode: "+256", flag: "🇺🇬", country: "Uganda" },
  { code: "UA", dialCode: "+380", flag: "🇺🇦", country: "Ukraine" },
  { code: "AE", dialCode: "+971", flag: "🇦🇪", country: "United Arab Emirates" },
  { code: "GB", dialCode: "+44", flag: "🇬🇧", country: "United Kingdom" },
  { code: "US", dialCode: "+1", flag: "🇺🇸", country: "United States" },
  { code: "UY", dialCode: "+598", flag: "🇺🇾", country: "Uruguay" },
  { code: "UZ", dialCode: "+998", flag: "🇺🇿", country: "Uzbekistan" },
  { code: "VU", dialCode: "+678", flag: "🇻🇺", country: "Vanuatu" },
  { code: "VA", dialCode: "+39-06", flag: "🇻🇦", country: "Vatican City" },
  { code: "VE", dialCode: "+58", flag: "🇻🇪", country: "Venezuela" },
  { code: "VN", dialCode: "+84", flag: "🇻🇳", country: "Vietnam" },
  { code: "YE", dialCode: "+967", flag: "🇾🇪", country: "Yemen" },
  { code: "ZM", dialCode: "+260", flag: "🇿🇲", country: "Zambia" },
  { code: "ZW", dialCode: "+263", flag: "🇿🇼", country: "Zimbabwe" }
];

// Get a country code object by country code
export function getCountryByCode(code: string) {
  return countryCodes.find(country => country.code === code);
}

// Get a country code object by dial code
export function getCountryByDialCode(dialCode: string) {
  return countryCodes.find(country => country.dialCode === dialCode);
}